import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { EcosystemGallery } from "@/components/ecosystem/EcosystemGallery";
import { SectionHeader } from "@/components/ui/SectionHeader";
import { bizFacilities, bizFacilitiesHero } from "@/data/chpEcosystem";

export default function BizFacilitiesPage() {
  return <main className="bg-stone-50 pt-16"><section className="relative isolate flex min-h-[420px] items-center overflow-hidden bg-green-950 sm:min-h-[460px]"><Image src={bizFacilitiesHero} alt="CHP 12 Biz Facilities" fill priority unoptimized sizes="100vw" className="object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-r from-black/70 via-black/50 to-black/60" /><div className="relative mx-auto w-full max-w-7xl px-4 py-20 text-center sm:px-6 lg:px-8"><p className="mb-5 inline-block rounded-full bg-green-900 px-4 py-1.5 text-xs font-semibold uppercase tracking-[0.18em] text-white">CHP Business Facilities</p><h1 className="text-4xl font-bold tracking-tight text-white sm:text-5xl md:text-6xl">12 CHP Biz Facilities</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-white/80">A collection of hospitality, learning, wellness, food, recreation, adventure, and creative experience concepts at CHP.</p></div></section><section className="py-16 lg:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeader eyebrow="The collection" title="Business concepts with a Himalayan setting" subtitle="Explore the facilities envisioned to support memorable, varied experiences across the CHP ecosystem." /><div className="mt-12"><EcosystemGallery items={bizFacilities} /></div></div></section><section className="bg-green-950 py-16 text-center"><div className="mx-auto max-w-3xl px-4 sm:px-6"><SectionHeader light eyebrow="Explore CHP" title="See what is possible in the mountains." subtitle="Get in touch with CHP for more information about these business facilities." /><Link href="/contact" className="mt-8 inline-flex items-center gap-2 rounded-full bg-orange-500 px-7 py-3.5 text-sm font-semibold text-white transition-all hover:-translate-y-0.5 hover:bg-orange-400">Contact CHP <ArrowRight className="h-4 w-4" /></Link></div></section><section className="bg-white py-10 text-center"><Link href="/" className="inline-flex items-center gap-2 rounded-full bg-green-900 px-8 py-3 font-semibold text-white transition-all hover:-translate-y-0.5 hover:bg-green-800"><ArrowLeft className="h-4 w-4" />Back to Home</Link></section></main>;
}
